### ISSUE TITLE
Knowledge base

### ISSUE THREAD

**Issue by Horcon** [MarkusAJacobsen/PGC#12]

**Comment by MarkusAJacobsen** [comment]
Is it possible to get a little more info on this one @Horcon @gurostorlien ?

**Comment by Horcon** [comment]
Tipper det er ment til å være en sånn "wiki" request type, som vil beskrive hva planten er og sånt. Så du kan gå inn i knowledge base, se hva slags typer planter man kan jobbe med, få info om det. Er ikke helt sikker på det da, men ingen andre issues ser ut til å peke mot den funksjonaliteten.

**Comment by MarkusAJacobsen** [comment]
`Plant-HAS_GUIDE->Guide`

**Comment by MarkusAJacobsen** [comment]
* Guides should be able to share stages. 
* Guides and stages should be able to update
* Get guide, guides, stages
